### ISSUE TITLE
Project health ?

### ISSUE THREAD

**Issue by xens** [aiden0z/guacamole-auth-jwt#10]
Hi, I'm wondering what's the state of this project, sound really interesting but haven't seen much activity for quite some time now. Does it still work with recent Guacamole releases ?

**Comment by aiden0z** [comment]
I will release a version for guacamole 1.5.2 as soon as possible.

**Comment by aiden0z** [comment]
hi  @xens  the v1.5.4 version is released, I will continue to maintain the project.
