### ISSUE TITLE
"guacamole-auth-jwt-1.0.0.jar" could not be loaded: Authentication provider class cannot be loaded (wrong version of API?).

### ISSUE THREAD

**Issue by epinna** [aiden0z/guacamole-auth-jwt#2]
Hello,

I just compiled guacamole-client and guacamole-auth-jwt with the same version of jdk/jdr but I've got this error on starting:

```
guac_1     | 14:01:31.725 [localhost-startStop-1] ERROR o.a.g.extension.ExtensionModule - Extension "guacamole-auth-jwt-1.0.0.jar" could not be loaded: Authentication provider class cannot be loaded (wrong version of API?).
```

Any idea why?

**Comment by epinna** [comment]
Fixed changing the namespaces according to the new guacamole-client.

**Comment by carlosmc96** [comment]
Hello epinna,

I have a similar error, how you change the namespaces for you case?

thanks

**Comment by epinna** [comment]
I think the author already fixed this error, changing from org.glyptodon.guacamole.* to org.apache.guacamole.* from version 1.0.0 to 1.0.1.

https://github.com/aiden0z/guacamole-auth-jwt/commit/45b306546c128b8f1b16980a3389b99ba9f08d84#diff-da28c94040e5af4daf5930b2b8862734
