### ISSUE TITLE
Update compatibility

### ISSUE THREAD

**Issue by gormux** [aiden0z/guacamole-auth-jwt#7]
Are there plans to update compatibility with guacamole 1.0 ?

**Comment by aronson** [comment]
I just recompiled it with the version string changed and it worked fine.

**Comment by gormux** [comment]
OK, thanks for the info.

**Comment by retnilps** [comment]
Hi, I tried recompiling but got this error on jar load under tomcat:

`Extension "guacamole-auth-jwt-1.0.0.jar" could not be loaded: Authentication provider class cannot be loaded (wrong version of API?)`

Any idea on what I'm doing wrong?

@aronson Can you please provide the recompiled version for 1.0.0?

**Comment by aiden0z** [comment]
The version has updated.
