### ISSUE TITLE
How do I install the plugin?

### ISSUE THREAD

**Issue by benspring** [aiden0z/guacamole-auth-jwt#8]
I have a softlink for the extension: guacamole-auth-jwt-0.9.14.jar -> /home/ubuntu/custom/guacamole-auth-jwt/build/libs/guacamole-auth-jwt-0.9.14.jar

I build this in gradle build, but feel I am royally missing a step. What am I doing wrong?

**Comment by benspring** [comment]
I don't get any errors when I restart my server, but the python script just returns 403.

**Comment by benspring** [comment]
`'{"message":"Invalid login","translatableMessage":{"key":"Invalid login","variables":null},"statusCode":null,"expected":[{"name":"username","type":"USERNAME"},{"name":"password","type":"PASSWORD"}],"type":"INVALID_CREDENTIALS"}'`

Adding 'GUAC_USERNAME': 'guacadmin' and 'GUAC_PASSWORD': 'guacadmin', to the payload doesn't work/

**Comment by benspring** [comment]
Oh and nothing was added to my guacamole.properties usermapping

**Comment by aiden0z** [comment]
The README file has updated to include installation and configuration content.
